version: '3.8'

services:
  mysql:
    build:
      context: .
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: taxi_app
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
